[project]
name = "tsbotrpi"
version = "0.1.0"
description = "TeamSpeak bot with ClientQuery control"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
	"python-dotenv",
	"ts3>=2.0.0b2",
	"ts3query>=2.0.1",
	"psutil>=5.9.0",
	"requests>=2.32.5",
]
